### ISSUE TITLE
Depthmaps format

### ISSUE THREAD

**Issue by adamroszyk** [andyzeng/tsdf-fusion#12]
HI,
I have a depthmaps that looks like this: [click](https://ibb.co/b4caEn)

I've tried using them in your code in the form as show on the picture, and after making them grayscale, but generated point-cloud seems to be empty with those.

Any advices - how I should prepare pictures to make them work with your code ?

Regards.

**Comment by andyzeng** [comment]
Depth maps should be saved in format: 16-bit PNG, depth in millimeters.

**Comment by adamroszyk** [comment]
Ok, thanks for quick answer - what about the resolution - does it have to be 640x480. or I can just change it in code - and it should work ?

**Comment by andyzeng** [comment]
Changing it should work. I haven't tested it though. Keep in mind that your camera intrinsics matrix `cam_k` will likely also have to change.

**Comment by adamroszyk** [comment]
Is it possible to apply different camera intrinsics to different frames ?
My frames are from iPhone, and it changes the camera intrinsics matrix every shoot.

**Comment by andyzeng** [comment]
It's possible, but you'll have to modify `demo.cu` so that it changes `cam_K` as it's looping through depth frames.

**Comment by adamroszyk** [comment]
Perfect, thanks again !

**Comment by B-Betty** [comment]
hello, @adamroszyk 
how do you convert image 32-bit to 16-bit as with as depth in millimeters?
