### ISSUE TITLE
Doesn't handle camera rotations proplery

### ISSUE THREAD

**Issue by kingsman142** [andyzeng/tsdf-fusion#21]
I'm currently using the Realsense D415 camera to gather RGBD data of an object, specifically a bottle. This camera is attached to the end-effector of a 6DOF robot. I use the robot to gather real-world pose coordinates of the camera. I use this kinematics data as the pose of the camera for both translation and rotation. This program works if I perform translation across one axis. However, it doesn't work when I perform a rotation.

Reading the papers linked in the README, I can't seem to figure out if their pose data is relative to the world's origin or if they're absolute physical locations, such as ones received from a robot's kinematics data. Do you know if I should perform any additional transformations on my pose data, similar to how the C++ programs calculate the inverse of the base frame and multiply that with each subsequent frame?

The first image is with the camera just performing a translation across one axis. The second image is the camera performing a translation across the same axis, but also performing a 0 to 360 degree rotation along the way. 

EDIT: By the way, I have double-checked the camera intrinsics, and have used two different realsense depth cameras and I'm encountering similar issues in both. Also, I have verified the positions of the end-effector (which is carrying the camera) are correct.

![python-translation](https://user-images.githubusercontent.com/1689017/60232849-d414c680-98d8-11e9-8a61-2be0fb12ddfb.png)

![python-translation-with-rotation](https://user-images.githubusercontent.com/1689017/60232858-dbd46b00-98d8-11e9-8b43-6bc70a5f5076.png)

**Comment by jly0810** [comment]
Hello, I have encountered a similar problem. How did you solve it? This problem has troubled me for a long time. Thank you

**Comment by H-tr** [comment]
This might because of different world coordination type. This project by default is using OpenCV camera coordinate system while your input might be OpenGL coordinate system. To convert it, you can try
```python
mat[2, :] *= -1
mat = mat[np.array([1, 0, 2, 3]), :]
mat[0:3, 1:3] *= -1
```
where `mat` is your extrinsic.

**Comment by liyuan-qiu** [comment]
This is how to transform the pose from Unity to TSDF_fusion

def transform_unity_to_tsdf_fusion(tx, ty, tz, rx, ry, rz, rw):
    """
    Transform Unity coordinates to TSDF Fusion coordinate system.
    Unity is left-handed (X=Forward, Y=Up, Z=Right).
    TSDF Fusion is right-handed (X=Forward, Y=Down, Z=Right).
    """
    # Transform translation
    tx_new = tx
    ty_new = -ty  # Flip Y-axis
    tz_new = tz   # Z-axis remains the same

    # Convert quaternion to rotation matrix
    rotation_matrix = quat2mat([rw, rx, ry, rz])

    # Define the transformation matrix to flip the Y-axis
    flip_y_matrix = np.array([
        [1,  0,  0],
        [0, -1,  0],  # Flip Y-axis
        [0,  0,  1]
    ])

    # Apply the transformation to the rotation matrix
    transformed_rotation_matrix = flip_y_matrix @ rotation_matrix @ flip_y_matrix.T

    # Convert the transformed rotation matrix back to a quaternion
    rw_new, rx_new, ry_new, rz_new = mat2quat(transformed_rotation_matrix)

    return tx_new, ty_new, tz_new, rx_new, ry_new, rz_new, rw_new
